"""
" File ./.vimrc
"
" Quick notes:
"   F6 toggles spellcheck
"   F5 toggles paste mode
"
"""

" Load vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/vundle'

" System
Plugin 'scrooloose/nerdtree.git'
Plugin 'davidhalter/jedi-vim'
Plugin 'tpope/vim-fugitive'
Plugin 'bling/vim-airline'

" Syntax
Plugin 'scrooloose/syntastic'
Plugin 'fatih/vim-go'

call vundle#end()
" Now we can turn our filetype functionality back on
filetype plugin indent on

" Coloring is good -- requires terminal theme suport
syntax enable
set background=dark
colorscheme vimbrant

" Tabs to 2 spaces
set shiftwidth=2
set tabstop=2

" autoindent
set autoindent

" Highlight current line
set cursorline
hi CursorLine   cterm=NONE ctermbg=233                              " Highlight current line

" toggle pasting to deal with autoindent
set pastetoggle=<F5>

" Status line --- not needed if vim-airline is working
set statusline=                                                     " clear the statusline for when vimrc is reloaded
set statusline+=%-3.3n\                                             " buffer number
set statusline+=%f\                                                 " file name
set statusline+=%h%m%r%w                                            " flags
set statusline+=[%{strlen(&ft)?&ft:'none'},                         " filetype
set statusline+=%{strlen(&fenc)?&fenc:&enc},                        " encoding
set statusline+=%{&fileformat}]                                     " file format
set statusline+=%=                                                  " right align
set statusline+=%{synIDattr(synID(line('.'),col('.'),1),'name')}\   " highlight
set statusline+=%10((%l/%L,%c)%)\                                   " line and column
set statusline+=%P                                                  " percentage of file

" cool tab completion stuff
set wildmenu
set wildmode=list:longest,full

" enable mouse support
set mouse=a

" line numbers
set number

" searching - ignore co<F6>ase and AI
set ignorecase
set smartcase

" toggle spelling with F4 key
map <F6> :set spell!<CR><Bar>:echo "Spell Check: " . strpart("OffOn", 3 * &spell, 3)<CR>

" beeps are annoying
set visualbell

" Search
set hlsearch

" Title
set title

" Ruler
set ruler

" Always show status line
set laststatus=2

" Swap
set directory=/tmp//                                                " Swap files
set backupskip=/tmp/*,/private/tmp/*

" HTML configurations
autocmd FileType html setlocal shiftwidth=2 tabstop=2 softtabstop=2 noexpandtab

" C configurations
autocmd FileType c setlocal colorcolumn=80 

" Python configurations
autocmd FileType python setlocal shiftwidth=4 expandtab tabstop=4 softtabstop=4
autocmd FileType python setlocal colorcolumn=80

" Strip trailing whitespace (F7)
function! StripWhitespace()
  let save_cursor = getpos(".")
  let old_query = getreg('/')
  :%s/\s\+$//e
  call setpos('.', save_cursor)
  call setreg('/', old_query)
endfunction
map <F7> :call StripWhitespace()<CR>

" syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_python_checkers = ['pyflakes']
let g:synastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = ' -std=c++11 -stdlib=libc++'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_error_symbol = "✗"
let g:syntastic_warning_symbol = "⚠"
let g:syntastic_mode_map = { "mode": "active", "active_filetypes": [], "passive_filetypes": ["tex"] }
nnoremap <F8> :SyntasticCheck<CR> :SyntasticToggleMode<CR>

" airline settings
let g:Powerline_symbols = 'fancy'
let g:airline_powerline_fonts = 1

" NERDTree
map <C-k> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | end

" Exit insert with jj.
imap jk <esc>
