# Path to your oh-my-zsh installation.
export ZSH=/Users/jholliman/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="agnoster"
DEFAULT_USER="jholliman"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(git docker)

# User configuration

source $ZSH/oh-my-zsh.sh

# GO
export GOROOT=~/Documents/go
export GOPATH=$GOROOT/src

# Editor
export EDITOR='vim'

# Remote git server
export REMOTE_GIT_USER_HOST=jhh3
export REMOTE_GIT_PATH=/home/git
export JHH3_LOG="/home/www/my-site/jhh3.log"

# PATH variable
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=/Users/jholliman/Documents/ngrok-app:$PATH
export PATH=$GOROOT/bin:$PATH
export PATH=/usr/texbin:$PATH
export PATH=/Users/jholliman/Documents/personal/remote-git-init:$PATH
export PATH=/Users/jholliman/Documents/personal/scripts:$PATH

# Set personal aliases
alias vundle="vim +PluginInstall +qall"

# ls after a cd
function chpwd() {
	emulate -L zsh
	ls -a
}

# Auto generated
