# Path to your oh-my-zsh installation.
export ZSH=/Users/jholliman/.oh-my-zsh

# oh-my-zsh theme
ZSH_THEME="agnoster"

# oh-my-zsh plugins
plugins=(git docker)

# User configuration
DEFAULT_USER="jholliman"
source $ZSH/oh-my-zsh.sh

# Editor
export EDITOR='vim'

# Remote git server
export REMOTE_GIT_USER_HOST=jhh3
export REMOTE_GIT_PATH=/home/git
export JHH3_LOG="/home/www/my-site/jhh3.log"

# PATH variable
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=/Users/jholliman/Documents/ngrok-app:$PATH     # ngrok
export PATH=/usr/texbin:$PATH                              # LaTeX

# Set personal aliases
alias vundle="vim +PluginInstall +qall"

# ls after a cd
function chpwd() {
	emulate -L zsh
	ls -a
}

# Auto generated
