# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# oh-my-zsh theme
ZSH_THEME="robbyrussell"

# oh-my-zsh plugins
plugins=(git docker)

# User configuration
DEFAULT_USER=`id -un`
source $ZSH/oh-my-zsh.sh

# Editor
export EDITOR='vim'

# Remote git server
export REMOTE_GIT_USER_HOST=jhh3
export REMOTE_GIT_PATH=/home/git
export JHH3_LOG="/home/www/my-site/jhh3.log"

# PATH variable
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=~/Documents/ngrok-app:$PATH                    # ngrok
export PATH=/usr/texbin:$PATH                              # LaTeX

# Right prompt
# NOTE : Slows down zsh because it takes a bit to the fetch the weather.
#WEATHER=~/Dropbox/personal/dotfiles/bin/get-temp.py
#function weather {
#	echo `$WEATHER 94035` 2>/dev/null
#}
#RPROMPT='$(weather)'

# Set personal aliases
alias vundle="vim +PluginInstall +qall"

# ls after a cd
function chpwd() {
	emulate -L zsh
	ls -a
}

# Auto generated
