---
- name: Install python-dev (so the next commands won't fail).
  become: true
  apt: name=python-dev state=installed

- name: Apt update
  become: true
  apt: update_cache=yes

- name: Install aptitude, python-apt, and pip (so the next commands won't fail)
  become: true
  apt: name={{item}} state=installed
  with_items:
      - aptitude
      - python-pip
      - python-dev
      - build-essential
      - git
      - cmake
      - zsh
      - jq

- name: Install docker-py to use docker module
  become: true
  pip:
    name: docker-py

